spring:
  cloud:
    function:
      definition: retailcoOrderUpdateValidatedV1B2CFurnitureConsumer
    stream:
      bindings:
        retailcoOrderUpdateValidatedV1B2CFurnitureConsumer-in-0:
          destination: retailco/order/update/validated/v1/B2C/furniture
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: 'localhost:55555'
                msgVpn: default
                clientUsername: default
                clientPassword: default
logging:
  level:
    root: info
    org:
      springframework: info

