name: Netlify Preview Builder
on:
  pull_request_target: 
    branches: [ master ]

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
          submodules: recursive
      - name: Checkout PR
        run: cd site/solace-dev-codelabs && git fetch origin pull/${{ github.event.pull_request.number }}/head:temp && git checkout temp
      - name: build site
        run: cd site && npm i && npm run dist
      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@v1.1.7
        with:
          publish-dir: './site/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}