name: Build Netlify Preview
on:
  pull_request_target:
    branches: [ master ]
    paths:
      - markdown/**

jobs:
  Build_Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
        with:
          go-version: '1.20.5'
        
      - name: Install node 24.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '24.x'
      
      - name: Checkout Current Commit
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          path: main

      - name: Checkout claat repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          repository: SolaceDev/google-tools
          path: google-tools
      
      - name: Checkout site repo
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
          submodules: recursive
          path: codelabs-site
      
      - name: Build claat
        run: cd google-tools/claat; go build .
      
      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v40
        with:
          files: | 
            **.md
          path: main
        
      - name: Export markdown files into site dir
        run: |
          for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
            folder="$(basename $file .md)"
            google-tools/claat/claat export -o codelabs-site/site/solace-dev-codelabs/codelabs main/$file
          done
          cd codelabs-site/site && npm ci && npm run dist

      - name: Netlify Deploy
        uses: nwtgck/actions-netlify@0798b5c54f7048599df8ff253d1d25edfe4e8ac1 # v1.1.7
        with:
          publish-dir: 'codelabs-site/site/dist'
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

