name: Update Codelabs Site Repo
on:
  push: 
    branches: [ master ]

jobs:
  Checkout_Site_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site repo
        uses: actions/checkout@v2
        with:
          repository: SolaceDev/solace-dev-codelabs-site
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Update submodule
        run: |
          git submodule update --remote
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update submodule from github actions"
          git remote add upstream git@github.com:SolaceDev/solace-dev-codelabs-site.git
          git push upstream master
      # - name: Push the changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{secrets.API_TOKEN}}
      #     repository: SolaceDev/solace-dev-codelabs-site